const frasesMotivacionais = [
  "Na programação e na vida, você não precisa saber tudo de uma vez; só precisa ter coragem para começar e consistência para evoluir linha por linha.",
  "Assim como no treino, o código só melhora quando você repete, ajusta e insiste — a evolução é construída na constância.",
  "Carreira é como um projeto grande: você não executa tudo em um dia, mas avança um commit por vez até transformar ideia em realidade.",
  "Treinar o corpo e treinar a mente para programar têm algo em comum: ambos exigem disciplina, paciência e a capacidade de seguir mesmo quando a motivação falha.",
  "Na jornada de um programador, assim como no fitness, você só vê resultados quando passa a fazer mesmo nos dias em que não sente vontade.",
  "Seu futuro como profissional depende das pequenas escolhas de hoje: estudar por 30 minutos, treinar por 1 hora ou revisar aquele código que você está adiando.",
  "Não existe atalho para crescer na carreira ou no shape: existe esforço diário, foco e o compromisso de não desistir quando fica difícil.",
  "Programar é transformar lógica em impacto; treinar é transformar esforço em resultado — ambos te lembram que você sempre pode ser melhor do que ontem.",
  "Grandes oportunidades aparecem para quem constrói base, pratica fundamentos e se prepara enquanto ninguém está vendo.",
  "Seu shape, seu código e sua carreira têm um ponto em comum: todos são a consequência direta dos seus hábitos.",
  "O programador que estuda todos os dias vence o que espera cair inspiração; o atleta que treina sempre vence o que depende de motivação.",
  "A vida recompensa quem entende que evolução não vem do conforto, mas do esforço constante aplicado nas coisas que realmente importam.",
  "Um projeto bem feito começa com clareza, um corpo bem treinado começa com disciplina e uma carreira sólida nasce da soma dos dois.",
  "Quanto mais você evolui como pessoa, mais seus resultados aparecem como profissional — tudo começa de dentro para fora.",
  "Consistência é a linguagem universal do sucesso: seja na academia, no VS Code ou na construção da sua própria versão melhorada.",
  "A cada dia que você estuda, treina e se dedica à sua carreira, você se aproxima da vida que sempre quis viver.",
  "Programar exige lógica, treinar exige força, e crescer na vida exige coragem para fazer o que precisa ser feito mesmo sem aplausos.",
  "Seu código não melhora sozinho, seu shape não muda sem treino e sua carreira não avança sem atitude — tudo depende da sua ação diária.",
  "A diferença entre quem conquista e quem só sonha está na capacidade de manter a disciplina quando o motivacional desaparece.",
  "Você não precisa ser o melhor do mundo, só precisa ser melhor do que você era ontem — e isso já te coloca na direção do extraordinário."
];

const frasesBiblicas = [
  "O Senhor é o meu pastor; de nada terei falta. (Salmos 23:1)",
  "Tudo posso naquele que me fortalece. (Filipenses 4:13)",
  "Sejam fortes e corajosos. Não tenham medo nem fiquem desanimados, pois o Senhor, o seu Deus, estará com você por onde você andar. (Josué 1:9)",
  "Porque sou eu que conheço os planos que tenho para vocês, diz o Senhor, planos de fazê-los prosperar e não de causar dano, planos de dar-lhes esperança e um futuro. (Jeremias 29:11)",
  "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade. (Salmos 46:1)",
  "Mas os que esperam no Senhor renovarão as suas forças. Voarão alto como águias; correrão e não ficarão exaustos, andarão e não se cansarão. (Isaías 40:31)",
  "Entregue o seu caminho ao Senhor; confie nele, e ele agirá. (Salmos 37:5)",
  "Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito. (Romanos 8:28)",
  "Não fui eu que ordenei a você? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar. (Josué 1:9)",
  "O Senhor é a minha luz e a minha salvação; de quem terei temor? O Senhor é o meu forte refúgio; de quem terei medo? (Salmos 27:1)",
  "Venham a mim, todos os que estão cansados e sobrecarregados, e eu darei descanso a vocês. (Mateus 11:28)",
  "Por isso não tema, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa. (Isaías 41:10)",
  "Mil cairão ao teu lado, e dez mil à tua direita, mas não chegará a ti. (Salmos 91:7)",
  "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês. (1 Pedro 5:7)",
  "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio. (2 Timóteo 1:7)",
  "Elevo os olhos para os montes: de onde me virá o socorro? O meu socorro vem do Senhor, que fez o céu e a terra. (Salmos 121:1-2)",
  "O choro pode durar uma noite, mas a alegria vem pela manhã. (Salmos 30:5)",
  "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos. (Hebreus 11:1)",
  "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente. (Romanos 12:2)",
  "Tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens. (Colossenses 3:23)"
];